// category: todo|on-progress|done|revised

export const projects = [
  {
    id: 1,
    name: "Content Writer Content Writer Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 2,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 3,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
  {
    id: 4,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "revised",
  },
  {
    id: 5,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 6,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 7,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
  {
    id: 8,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "revised",
  },
  {
    id: 9,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 10,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 11,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
  {
    id: 12,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "revised",
  },
  {
    id: 13,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 14,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 15,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
  {
    id: 16,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "revised",
  },
  {
    id: 17,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 18,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 19,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
  {
    id: 20,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "revised",
  },
  {
    id: 21,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "todo",
  },
  {
    id: 22,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "on-progress",
  },
  {
    id: 23,
    name: "Content Writer",
    description: "Prepare proctor for client meeting",
    date: "2021-10-10",
    status: "done",
  },
];
